USE ROLE SYSADMIN;

CREATE DATABASE DBT_DB;
-- CREATE SCHEMA DBT_SCHEMA;
CREATE WAREHOUSE DBT_WH WITH WAREHOUSE_SIZE='XSMALL';

USE ROLE SECURITYADMIN;

CREATE USER DBT_USER WITH PASSWORD='dbt_user';
CREATE ROLE DBT_ROLE;

GRANT ROLE DBT_ROLE TO USER DBT_USER;
GRANT ROLE DBT_ROLE TO ROLE SYSADMIN;
GRANT OWNERSHIP ON DATABASE DBT_DB TO ROLE DBT_ROLE;
-- GRANT USAGE ON SCHEMA DBT_DB.DBT_SCHEMA TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;


REVOKE USAGE ON DATABASE DBT_DB FROM ROLE DBT_ROLE;

DROP SCHEMA DBT_DB.DBT_SCHEMA;