delete from EDW_DEV.ETL.INGESTION_METADATA_CONFIG;
select * from EDW_DEV.ETL.INGESTION_METADATA_CONFIG;
USE DATABASE EDW_DEV;
USE SCHEMA ETL;
-- New Table for testing Full Load
SET LOGICAL_NAME = 'Clarity';
SET SOURCE_TYPE = 'SQL Server';
SET DATABASE_NAME = 'fis_db';
SET SCHEMA_NAME = 'dbo';
SET SOURCE_TABLE_NAME = 'Orders';
SET DELTA_COLUMN = 'OrderID';
SET DELTA_VALUE = '-1';
SET CHANGE_TRACKING = '0';
SET ENABLED = '1';
SET PRIORITY_FLAG = '0';
SET ADF_LAST_LOAD_DT = '1900-01-01';
SET STAGE_LAST_LOAD_DT = '1900-01-01';
SET TARGET_LAST_LOAD_DT = '1900-01-011';
SET LAST_LOAD_DATE = '1900-01-01';
SET PAYLOAD ='N/A';
-- Call the Method
CALL INSERT_INTO_METADATA_CONFIG($LOGICAL_NAME, $SOURCE_TYPE, $DATABASE_NAME, $SCHEMA_NAME, $SOURCE_TABLE_NAME, $DELTA_COLUMN, $DELTA_VALUE, $CHANGE_TRACKING, $ENABLED, $PRIORITY_FLAG, $ADF_LAST_LOAD_DT, $STAGE_LAST_LOAD_DT, $TARGET_LAST_LOAD_DT, $LAST_LOAD_DATE, $PAYLOAD);
select * from EDW_DEV.ETL.INGESTION_METADATA_CONFIG;
-- Enable the new pipeline
update EDW_DEV.ETL.INGESTION_METADATA_CONFIG SET ENABLED = '1', CHANGE_TRACKING_TYPE = 'SQL Server';
-- Show orders quantity in the target table
select count(*) from datalake_dev.fis_db_dbo.orders;
select * from datalake_dev.fis_db_dbo.orders;
-- Show updated values in target table
select * from datalake_dev.fis_db_dbo.orders where shipcountry = 'TEST_COUNTRY';
-- Show products quantity in the stage table
select count(*) from stage_dev.fis_db_dbo.orders;
select * from stage_dev.fis_db_dbo.orders;
-- Product Table added for testing multiple tables
SET LOGICAL_NAME = 'Clarity';
SET SOURCE_TYPE = 'SQL Server';
SET DATABASE_NAME = 'fis_db';
SET SCHEMA_NAME = 'dbo';
SET SOURCE_TABLE_NAME = 'Products';
SET DELTA_COLUMN = 'ProductID';
SET DELTA_VALUE = '-1';
SET CHANGE_TRACKING = '1';
SET ENABLED = '1';
SET PRIORITY_FLAG = '0';
SET ADF_LAST_LOAD_DT = '1900-01-01';
SET STAGE_LAST_LOAD_DT = '1900-01-01';
SET TARGET_LAST_LOAD_DT = '1900-01-011';
SET LAST_LOAD_DATE = '1900-01-01';
SET PAYLOAD ='N/A';
-- Call the Method
CALL INSERT_INTO_METADATA_CONFIG($LOGICAL_NAME, $SOURCE_TYPE, $DATABASE_NAME, $SCHEMA_NAME, $SOURCE_TABLE_NAME, $DELTA_COLUMN, $DELTA_VALUE, $CHANGE_TRACKING, $ENABLED, $PRIORITY_FLAG, $ADF_LAST_LOAD_DT, $STAGE_LAST_LOAD_DT, $TARGET_LAST_LOAD_DT, $LAST_LOAD_DATE, $PAYLOAD);
-- Clear Environment for testing full load
DROP SCHEMA STAGE_DEV.FIS_DB_DBO;
DROP SCHEMA DATALAKE_DEV.FIS_DB_DBO;
CREATE SCHEMA STAGE_DEV.FIS_DB_DBO;
CREATE SCHEMA DATALAKE_DEV.FIS_DB_DBO;
GRANT ALL PRIVILEGES ON SCHEMA STAGE_DEV.FIS_DB_DBO TO ROLE EDW_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DATALAKE_DEV.FIS_DB_DBO TO ROLE EDW_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA EDW_DEV.ETL TO ROLE EDW_ROLE;



SELECT * FROM EDW_DEV.ETL.INGESTION_METADATA_CONFIG;

UPDATE EDW_DEV.ETL.INGESTION_METADATA_CONFIG SET CHANGE_TRACKING_TYPE='SQL Server', ENABLED = 1, CUSTOM_PARAMS='{ "clientId": "clientB"}' WHERE SOURCE_TABLE_NAME = 'Products';

UPDATE EDW_DEV.ETL.INGESTION_METADATA_CONFIG SET ENABLED=1 WHERE SOURCE_TABLE_NAME = 'Orders';

UPDATE EDW_DEV.ETL.INGESTION_METADATA_CONFIG SET CUSTOM_PARAMS='{ "clientId": "clientA"}' WHERE SOURCE_TABLE_NAME = 'Orders';

