USE DATABASE EDW_DEV;
USE SCHEMA ETL;

USE ROLE EDW_ROLE;
USE WAREHOUSE EDW_WH;

-- New Table for testing Full Load
SET LOGICAL_NAME = 'FIS';
SET SOURCE_TYPE = 'SQL Server';
SET DATABASE_NAME = 'fis_db';
SET SCHEMA_NAME = 'dbo';
SET SOURCE_TABLE_NAME = 'Orders';
SET DELTA_COLUMN = 'OrderID';
SET DELTA_VALUE = '-1';
SET CHANGE_TRACKING = '0';
SET ENABLED = '1';
SET PRIORITY_FLAG = '0';
SET ADF_LAST_LOAD_DT = '1900-01-01';
SET STAGE_LAST_LOAD_DT = '1900-01-01';
SET TARGET_LAST_LOAD_DT = '1900-01-011';
SET LAST_LOAD_DATE = '1900-01-01';
SET PAYLOAD ='N/A';

-- Call the Method
CALL INSERT_INTO_METADATA_CONFIG($LOGICAL_NAME, $SOURCE_TYPE, $DATABASE_NAME, $SCHEMA_NAME, $SOURCE_TABLE_NAME, $DELTA_COLUMN, $DELTA_VALUE, $CHANGE_TRACKING, $ENABLED, $PRIORITY_FLAG, $ADF_LAST_LOAD_DT, $STAGE_LAST_LOAD_DT, $TARGET_LAST_LOAD_DT, $LAST_LOAD_DATE, $PAYLOAD);

-- Enable the new pipeline
UPDATE EDW_DEV.ETL.INGESTION_METADATA_CONFIG SET CHANGE_TRACKING = '1', CHANGE_TRACKING_TYPE='SQL Server', ENABLED = 1, CUSTOM_PARAMS='{ "clientId": "clientA"}' WHERE SOURCE_TABLE_NAME = 'Orders';

-- Product Table added for testing multiple tables
SET LOGICAL_NAME = 'FIS';
SET SOURCE_TYPE = 'SQL Server';
SET DATABASE_NAME = 'fis_db';
SET SCHEMA_NAME = 'dbo';
SET SOURCE_TABLE_NAME = 'Products';
SET DELTA_COLUMN = 'ProductID';
SET DELTA_VALUE = '-1';
SET CHANGE_TRACKING = '1';
SET ENABLED = '1';
SET PRIORITY_FLAG = '0';
SET ADF_LAST_LOAD_DT = '1900-01-01';
SET STAGE_LAST_LOAD_DT = '1900-01-01';
SET TARGET_LAST_LOAD_DT = '1900-01-011';
SET LAST_LOAD_DATE = '1900-01-01';
SET PAYLOAD ='N/A';

-- Call the Method
CALL INSERT_INTO_METADATA_CONFIG($LOGICAL_NAME, $SOURCE_TYPE, $DATABASE_NAME, $SCHEMA_NAME, $SOURCE_TABLE_NAME, $DELTA_COLUMN, $DELTA_VALUE, $CHANGE_TRACKING, $ENABLED, $PRIORITY_FLAG, $ADF_LAST_LOAD_DT, $STAGE_LAST_LOAD_DT, $TARGET_LAST_LOAD_DT, $LAST_LOAD_DATE, $PAYLOAD);

-- Enable the new pipeline
UPDATE EDW_DEV.ETL.INGESTION_METADATA_CONFIG SET CHANGE_TRACKING = '1', CHANGE_TRACKING_TYPE='SQL Server', ENABLED = 1, CUSTOM_PARAMS='{ "clientId": "clientB"}' WHERE SOURCE_TABLE_NAME = 'Products';