USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE EXTERNAL VOLUME AZURE_VOLUME_DEV
    STORAGE_LOCATIONS =
    (
        (
            NAME = 'azure-volume-dev'
            STORAGE_PROVIDER = 'AZURE'
            STORAGE_BASE_URL = 'azure://eastus2devicebergdemosa.blob.core.windows.net/iceberg-demo/'
            AZURE_TENANT_ID = '1acc27f8-8478-4411-a70d-8a7eca63c288'
        )
    );


GRANT USAGE ON EXTERNAL VOLUME AZURE_VOLUME_DEV TO ROLE EDW_ROLE;
    
DESC EXTERNAL VOLUME AZURE_VOLUME_DEV; -- look for AZURE_CONSENT_URL and AZURE_MULTI_TENANT_APP_NAME


SELECT SYSTEM$VERIFY_EXTERNAL_VOLUME('AZURE_VOLUME_DEV');

CREATE SCHEMA TEST;

CREATE STAGE MY_STAGE;
SHOW EXTERNAL VOLUMES;

CREATE ICEBERG TABLE my_iceberg_table (amount int)
  CATALOG = SNOWFLAKE
  EXTERNAL_VOLUME = AZURE_VOLUME_DEV
  BASE_LOCATION = my_iceberg_table;

DROP TABLE my_iceberg_table;

CREATE ICEBERG TABLE IF NOT EXISTS MyTable
(
    ID STRING NULL,
    NAME STRING NULL,
    CREATED_AT TIMESTAMP_NTZ NULL,
    SYS_CHANGE_VERSION STRING NULL,
    SYS_CHANGE_OPERATION STRING NULL,
    LOAD_DATETIME TIMESTAMP NULL,
    LOAD_PROCESS STRING NULL
) 
CATALOG = SNOWFLAKE 
EXTERNAL_VOLUME = AZURE_VOLUME_DEV 
BASE_LOCATION = MyTable.Test;

DROP TABLE MyTable;


CREATE ICEBERG TABLE IF NOT EXISTS TestIcebergTable (
    id INT,
    name STRING,
    is_active BOOLEAN,
    created_at TIMESTAMP_NTZ,
    amount DECIMAL(10, 2),
    binary_data BINARY,
    notes STRING
) 
CATALOG = SNOWFLAKE 
EXTERNAL_VOLUME = AZURE_VOLUME_DEV
BASE_LOCATION = TestIcebergTable;

DROP TABLE TestIcebergTable;


COPY INTO my_iceberg_table 
FROM '@MY_STAGE/test.csv'
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

SELECT * FROM MY_ICEBERG_TABLE;

insert into my_iceberg_table values (100), (200), (300);

COPY INTO my_iceberg_table


CREATE OR REPLACE CATALOG INTEGRATION icebergCatalogInt
  CATALOG_SOURCE = OBJECT_STORE
  TABLE_FORMAT = ICEBERG
  ENABLED = TRUE;

CREATE ICEBERG TABLE my_iceberg_table
  CATALOG='icebergCatalogInt'
  EXTERNAL_VOLUME = 'orders_vol'
  CATALOG_TABLE_NAME = 'my_iceberg_table';

CREATE ICEBERG TABLE myIcebergTable
  EXTERNAL_VOLUME='orders_vol'
  CATALOG='icebergCatalogInt'
  METADATA_FILE_PATH='myIcebergTable/metadata/v1.metadata.json';
